Change1
YoshithaRathnayake/NEW-YOSHITHA-WEBSITE pull request #105
Opened 2022-10-15 06:26 UTC by Hiresh23

## Purpose
To add lines in the contact sections
#<84>

## Goals
It will provide a way for site viewers to get in touch

## Approach
Just a section with necessary text and apply related css

### Screenshots
![Screenshot 2022-10-15 114828](https://user-images.githubusercontent.com/99505876/195972369-c60b94df-4793-4ca9-a429-1538fe910922.png)

  
### Preview Link

https://pr-8f7d1fd7a4ce12e0f3d1988187ca4955d1a3f142-NEW-YOSHITHA-WEBSITE.surge.sh

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-10-15 06:37 UTC, YoshithaRathnayake requested changes
For the issue number in the purpose don't put it in <> tags

2022-10-15 06:38 UTC, YoshithaRathnayake requested changes
Put the preview link as this https://pr-105-NEW-YOSHITHA-WEBSITE.surge.sh

2022-10-15 06:43 UTC, YoshithaRathnayake requested changes
Change the topic of this pr as the topic of the issue

2022-10-15 09:08 UTC, Hiresh23 commented
Done

2022-10-15 09:11 UTC, Hiresh23 commented
Check now

2022-10-15 09:33 UTC, YoshithaRathnayake requested changes

2022-10-15 09:33 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +    left: 380px;
Remove the left and align the text center

2022-10-15 09:36 UTC, YoshithaRathnayake requested changes

2022-10-15 09:36 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +    padding: 18px 40px;
Undo these unwanted changes

2022-10-15 09:36 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +    margin: 80px;
Undo these unwanted changes

2022-10-15 09:36 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +    justify-content: center;
Undo these unwanted changes

2022-10-15 09:36 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +.ix{
Undo these unwanted changes

2022-10-15 09:36 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +    height: 000px;
Undo these unwanted changes

2022-10-15 09:36 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +#about-section{
Undo these unwanted changes

2022-10-15 09:36 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> -    z-index: -1;
Undo these unwanted changes

2022-10-15 09:37 UTC, YoshithaRathnayake requested changes

2022-10-15 09:37 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +input ,label{
There isn't a form so remove these unwanted codes

2022-10-15 09:38 UTC, YoshithaRathnayake requested changes

2022-10-15 09:38 UTC, YoshithaRathnayake commented on dark/index.html
> +            ><img class ="ix" src="https://img.icons8.com/color/48/000000/whatsapp--v1.png" alt="Whatsapp Icon"
Remove these unwanted changes

2022-10-15 09:39 UTC, YoshithaRathnayake requested changes
Remove the languages image

2022-10-16 02:23 UTC, YoshithaRathnayake requested changes
Resolve the conflicts

2022-10-16 02:30 UTC, YoshithaRathnayake requested changes
@Hiresh23,

- First, delete this branch and the pr.
- Create a new branch and checkout it.
- After that git remote add upstream https://github.com/YoshithaRathnayake/NEW-YOSHITHA-WEBSITE.git
- git fetch upstream
- git reset --hard upstream/main
- git pull upstream main
- After that do the changes.
- Add the changes and commit them
- git push origin BRANCH_NAME

2022-10-21 01:10 UTC, closed without merging

2022-10-21 12:52 UTC, Hiresh23 commented
Please remove spam

2022-10-21 12:54 UTC, Hiresh23 commented
I could not complete because my exam are going