Change2
YoshithaRathnayake/NEW-YOSHITHA-WEBSITE pull request #106
Opened 2022-10-15 06:41 UTC by Hiresh23

## Purpose
To add languages and icon
#<issue-number>

## Goals
People can know in which languages they can contact

## Approach
Just add a section in which a paragraph tag is used for text and image tag for logo

### Screenshots
![Screenshot 2022-10-15 120711](https://user-images.githubusercontent.com/99505876/195973180-3b71a20f-071c-4db5-901e-1ad6f6cdf1b5.png)

  
### Preview Link

https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-10-15 06:44 UTC, YoshithaRathnayake requested changes
Change the topic of this pr as the topic of the issue

2022-10-15 06:45 UTC, YoshithaRathnayake requested changes
Put the preview link as this https://pr-106-new-yoshitha-website.surge.sh/

2022-10-15 06:45 UTC, YoshithaRathnayake requested changes
For the issue number in the purpose don't put it in <> tags

2022-10-15 09:10 UTC, Hiresh23 commented
Done

2022-10-15 09:40 UTC, YoshithaRathnayake requested changes

2022-10-15 09:40 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +#contact-section .context1{
Remove these early commits

2022-10-15 09:41 UTC, YoshithaRathnayake requested changes

2022-10-15 09:41 UTC, YoshithaRathnayake commented on dark/index.html
> +             <section class="context1"><p>Want to get in touch with me? Fill out the form with your inquiry or mail me,you can also connect with me on social media platforms on above given links</p>
Remove these early commits

2022-10-19 16:08 UTC, closed without merging

2022-10-21 12:55 UTC, Hiresh23 commented
Bro please remove spam

2022-10-21 12:55 UTC, Hiresh23 commented
I would work on the website my exam were going so i could not do

2022-10-21 20:46 UTC, Hiresh23 commented
now what is the use i have been disqualified because of you

2022-10-21 20:46 UTC, Hiresh23 commented
too late i have been disqualified because of you

2022-10-22 02:19 UTC, YoshithaRathnayake commented
> too late i have been disqualified because of you

So you should have tell it to me early

2022-10-22 02:20 UTC, YoshithaRathnayake commented
> too late i have been disqualified because of you

If you want create a new github account and do hacktobefest no worries.

2022-10-22 02:21 UTC, YoshithaRathnayake commented
> too late i have been disqualified because of you

create new account I will help you @Hiresh23

2022-10-22 02:36 UTC, YoshithaRathnayake commented
> too late i have been disqualified because of you

don't tell me bcs of you bcs you should have tell it to me early like I am having exams so I can't do this. If you told like that I won't put the spam label @Hiresh23

2022-10-22 02:37 UTC, YoshithaRathnayake commented
> > too late i have been disqualified because of you
> 
> don't tell me bcs of you bcs you should have tell it to me early like I am having exams so I can't do this. If you told like that I won't put the spam label @Hiresh23

I don't know no you reason what are you not doing so should tell it to me otherwise I will put spam label

2022-10-22 15:38 UTC, YoshithaRathnayake commented
If you disqualified or if you have exams they both are same bcs if its disqualified you can't do hacktoberfest, if you face your exams you won't be able to do hacktoberfest so no need to worry about this how ever you won't be able to do hacktoberfest @Hiresh23