Contact Sectiion
YoshithaRathnayake/NEW-YOSHITHA-WEBSITE pull request #120
Opened 2022-10-24 19:34 UTC by theotsuaneng

Add a sentence to contact section -TheoTsuaneng

## Purpose

The purpose of this Pull Request is to fix #<issue-number>

## Goals

## Approach

### Screenshots

  
### Preview Link

https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2022-10-24 19:35 UTC, theotsuaneng commented
![Screenshot (59)](https://user-images.githubusercontent.com/61048380/197610560-7de35d9c-d051-4dcf-aa1f-f1ee99084325.png)

2022-10-25 09:56 UTC, YoshithaRathnayake requested changes

2022-10-25 09:56 UTC, YoshithaRathnayake commented on dark/assets/css/styles.css
> +    background: rgb(209, 38, 38);
Remove this color bcs the current color is looks good @theotsuaneng

2022-10-25 10:02 UTC, YoshithaRathnayake requested changes

2022-10-25 10:02 UTC, YoshithaRathnayake commented on dark/index.html
> +                    📚 Education : St. Anthony's College, Kandy.
Remove this full stop from this @theotsuaneng 

```suggestion
                    📚 Education : St. Anthony's College, Kandy

```

2022-10-25 10:04 UTC, YoshithaRathnayake requested changes

2022-10-25 10:04 UTC, YoshithaRathnayake commented on index.html
> +    <p>Contact me via Email, Message or connect me with social media accounts. Also send me any inquiries by filling in the form given just below</p>
Remove the sentence from the index.html bcs index.html means the pre-loader of this website @theotsuaneng

2022-10-25 10:23 UTC, theotsuaneng commented
Hi @YoshithaRathnayake I have resolved the stated issues.

2022-10-25 10:26 UTC, YoshithaRathnayake requested changes

2022-10-25 10:26 UTC, YoshithaRathnayake commented on dark/index.html
> +                <p>Contact me via Email, Message or connect me with social media accounts.
Can you align center the text @theotsuaneng

2022-10-25 10:45 UTC, YoshithaRathnayake requested changes

2022-10-25 10:45 UTC, YoshithaRathnayake commented on dark/index.html
> +                <style>
Don't use inline css just add wrap the text with a `center` tag

2022-10-25 10:58 UTC, theotsuaneng commented
@YoshithaRathnayake the css has been removed may you accept the pull.

2022-10-25 11:31 UTC, YoshithaRathnayake approved these changes
Good Job !
Thank You @theotsuaneng

2022-10-25 12:09 UTC, merged