Fix: Issue #222(changed Twitter link)
YoshithaRathnayake/NEW-YOSHITHA-WEBSITE pull request #238
Opened 2024-10-10 05:31 UTC by S-125

## Purpose

The purpose of this Pull Request is to fix #<issue-number>

## Goals

## Approach

### Screenshots

### Preview Link

https://pr-{PR_NUMBER}-NEW-YOSHITHA-WEBSITE.surge.sh/

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [ ] I have read and understood the development best practices guidelines
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 

## Test environment
 

## Learning

2024-10-10 05:31 UTC, S-125 commented
Please add hacktoberfest-accepted label to my PR before merging it.

2024-10-10 17:38 UTC, YoshithaRathnayake requested changes

2024-10-10 17:38 UTC, YoshithaRathnayake commented on dark/index.html
> +        <a href=" https://x.com/Yoshitha_R" target="_blank "><img src="https://img.icons8.com/?size=48&id=YfCbGWCWcuar&format=png&color=ffffff" alt="Twitter Icon" /></a>
Remove the space here @S-125 
```suggestion
        <a href="https://x.com/Yoshitha_R" target="_blank "><img src="https://img.icons8.com/?size=48&id=YfCbGWCWcuar&format=png&color=ffffff" alt="Twitter Icon" /></a>

```

2024-10-10 17:38 UTC, YoshithaRathnayake commented
> Please add hacktoberfest-accepted label to my PR before merging it.

Ah sure! So if he approve the PR according to the guidelines there are no problems you're hacktoberfest PR is accepted but I am doing the both steps so don't worry @S-125 And I am going to make a new hacktoberfest project

https://github.com/YoshithaRathnayake/Hacktoberfest-Project

SO keep in touch (Starred the rep)

2024-10-11 04:38 UTC, YoshithaRathnayake reviewed
Changes are fine!. Make sure you have completed these tasks! @S-125 

- [ ] Starred this repository

- [ ] Followed me on social media (Visit my GitHub profile for more info)

After doing these things I'll merge this for sure

2024-10-11 15:54 UTC, S-125 commented
@YoshithaRathnayake  I have done both

2024-10-11 18:42 UTC, YoshithaRathnayake commented
> @YoshithaRathnayake I have done both

Atleast follow me in github 😂🤌🏻

2024-10-11 18:44 UTC, S-125 commented
I am so sorry I followed u on insta and forgot about github

2024-10-12 02:19 UTC, YoshithaRathnayake commented
> I am so sorry I followed u on insta and forgot about github

Ah nice ♥ @S-125

2024-10-12 02:20 UTC, YoshithaRathnayake approved these changes
Good job! Thank you @S-125

2024-10-12 02:23 UTC, YoshithaRathnayake commented
So I am going to do a another hacktoberfest project soon so, if you couldn't complete the 4 tasks go keep in touch. @S-125 

https://github.com/YoshithaRathnayake/Hacktoberfest-Project

2024-10-12 02:23 UTC, merged